### ISSUE TITLE
Create test suite for the get_projected_points method.

### ISSUE THREAD

**Issue by LucaCappelletti94** [LucaCappelletti94/covidxpert#8]
The method [get_projected_points](https://github.com/LucaCappelletti94/covidxpert/blob/fc7114c1a0a9cacd55f2e8745e225739ea129fed/covidxpert/utils/get_projected_points.py#L4) is now integrated in the codebase.

@massimocavallin could you manage its codebase and validate it?

Thanks.

**Comment by LucaCappelletti94** [comment]
@massimocavallin I have fixed an issue within this function. Do pull the updates before proceeding further.

**Comment by massimocavallin** [comment]
I have fixed the function and added the tests.
Thanks.
