### ISSUE TITLE
Create test suite for fill blob methods

### ISSUE THREAD

**Issue by LucaCappelletti94** [LucaCappelletti94/covidxpert#9]
The method [get_projected_points](https://github.com/LucaCappelletti94/covidxpert/blob/9b6c44c7c0fbbcadd18c84c5500ef49c7051fddd/covidxpert/utils/remove_artefacts.py#L58) and [fill_small_black_blobs](https://github.com/LucaCappelletti94/covidxpert/blob/9b6c44c7c0fbbcadd18c84c5500ef49c7051fddd/covidxpert/utils/remove_artefacts.py#L73) are now integrated in the codebase.

@massimocavallin could you manage its codebase and validate it?

Thanks.

**Comment by massimocavallin** [comment]
I have fixed the function and added the tests.
